#!/usr/bin/env python3
"""Generate the compact manuscript tables from canonical evaluation CSVs."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_PUBLICATION = REPO_ROOT / "reports" / "publication"
DEFAULT_OUTPUT = REPO_ROOT / "paper" / "tables"

MODES = (
    ("Full system", "safemap_deterministic"),
    ("Without pointer roles", "safemap_without_pointer_roles"),
    ("Without safe signatures", "safemap_without_safe_signatures"),
    ("Without dependency grouping", "safemap_without_dependency_grouping"),
    ("Without idiom plans", "safemap_without_idiom_plans"),
    ("Without validation feedback", "safemap_without_validation_feedback"),
)


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _rows(path: Path, mode: str) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return [row for row in csv.DictReader(handle) if row["mode"] == mode]


def _verify_provenance(paths: list[Path]) -> str:
    commits = set()
    for path in paths:
        with path.open(newline="", encoding="utf-8") as handle:
            rows = list(csv.DictReader(handle))
        if not rows:
            raise ValueError(f"Evaluation CSV contains no rows: {path}")
        commits.update(row.get("git_commit", "") for row in rows)
        dirty = {row.get("git_dirty", "").lower() for row in rows}
        if dirty != {"false"}:
            raise ValueError(f"Manuscript input was not generated cleanly: {path}")
    if len(commits) != 1 or not next(iter(commits)):
        raise ValueError(f"Manuscript inputs use different commits: {sorted(commits)}")
    return next(iter(commits))


def _display_path(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def _integer(row: dict[str, str], field: str) -> int:
    value = row.get(field, "").strip()
    return int(float(value)) if value else 0


def _sum(rows: list[dict[str, str]], field: str) -> int:
    return sum(_integer(row, field) for row in rows)


def _cascade(label: str, path: Path) -> tuple[str, list[int]]:
    rows = _rows(path, "safemap_deterministic")
    return label, [
        _sum(rows, "total_units"),
        _sum(rows, "candidate_safe_units"),
        _sum(rows, "synthesis_supported_units"),
        _sum(rows, "generated_units"),
        _sum(rows, "compile_success_units"),
        _sum(rows, "policy_safe_units"),
        _sum(rows, "behaviorally_validated_units"),
    ]


def _write_cascade(path: Path, rows: list[tuple[str, list[int]]]) -> None:
    lines = [
        "% Generated by scripts/generate_manuscript_tables.py; do not edit.",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Development-only outcome cascade. ``Cand.'' denotes",
        r"\texttt{candidate\_safe}; ``Behav.'' denotes behaviorally validated",
        r"policy-safe output.}",
        r"\label{tab:development-cascade}",
        r"\resizebox{\columnwidth}{!}{%",
        r"\begin{tabular}{lrrrrrrr}",
        r"\toprule",
        "Corpus & Total & Cand. & Support & Gen. & Compile & Policy & Behav. \\\\",
        r"\midrule",
    ]
    lines.extend(
        f"{label} & " + " & ".join(str(value) for value in values) + r" \\"
        for label, values in rows
    )
    lines.extend([
        r"\bottomrule",
        r"\end{tabular}}",
        r"\end{table}",
        "",
    ])
    path.write_text("\n".join(lines), encoding="utf-8")


def _write_ablations(
    path: Path,
    example_csv: Path,
    module_csv: Path,
) -> list[dict[str, Any]]:
    values = []
    for label, mode in MODES:
        examples = _rows(example_csv, mode)
        modules = _rows(module_csv, mode)
        values.append({
            "label": label,
            "mode": mode,
            "example_accepted": _sum(examples, "behaviorally_validated_units"),
            "example_total": _sum(examples, "total_units"),
            "module_accepted": _sum(modules, "behaviorally_validated_units"),
            "module_total": _sum(modules, "total_units"),
        })
    lines = [
        "% Generated by scripts/generate_manuscript_tables.py; do not edit.",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Behaviorally validated units in component ablations.",
        r"Denominators include every function or dependency unit in each",
        r"development corpus.}",
        r"\label{tab:development-ablations}",
        r"\begin{tabular}{lrr}",
        r"\toprule",
        "Configuration & Microbenchmarks & Modules \\\\",
        r"\midrule",
    ]
    lines.extend(
        f"{item['label']} & {item['example_accepted']}/{item['example_total']} & "
        f"{item['module_accepted']}/{item['module_total']} " + r"\\"
        for item in values
    )
    lines.extend([
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        "",
    ])
    path.write_text("\n".join(lines), encoding="utf-8")
    return values


def _write_audit(
    path: Path,
    source_commit: str,
    inputs: dict[str, Path],
    cascade: list[tuple[str, list[int]]],
    ablations: list[dict[str, Any]],
) -> None:
    lines = [
        "# Development-result claim audit",
        "",
        "Generated by `scripts/generate_manuscript_tables.py`; do not edit by hand.",
        "",
        f"All source rows report clean Git commit `{source_commit}`.",
        "",
        "## Outcome cascade",
        "",
        "| Corpus | Total | Candidate | Supported | Generated | Compiled | Policy-safe | Behavioral |",
        "|---|---:|---:|---:|---:|---:|---:|---:|",
    ]
    lines.extend(
        f"| {label} | " + " | ".join(str(value) for value in values) + " |"
        for label, values in cascade
    )
    lines.extend([
        "",
        "## Ablation claims",
        "",
        "| Configuration | Microbenchmarks | Modules |",
        "|---|---:|---:|",
    ])
    lines.extend(
        f"| {item['label']} | {item['example_accepted']}/{item['example_total']} | "
        f"{item['module_accepted']}/{item['module_total']} |"
        for item in ablations
    )
    c2rust_rows = _rows(inputs["c2rust"], "c2rust_only")
    lines.extend([
        "",
        "## Additional manuscript checks",
        "",
        f"- Raw C2Rust accepted `{_sum(c2rust_rows, 'behaviorally_validated_units')}` "
        f"of `{_sum(c2rust_rows, 'candidate_safe_units')}` candidate-safe units under the shared policy.",
        "- The LLVM accepted-function identities were checked in the clean raw run: "
        "`loop`, `sqr`, `fade`, `lerp`, `ReverseBits32`, and `ReverseBits64`.",
        "- Miri is recorded as skipped in these frozen development rows and is not counted as a pass.",
        "",
        "## Input hashes",
        "",
    ])
    lines.extend(
        f"- `{_display_path(source)}`: `{_sha256(source)}`"
        for source in inputs.values()
    )
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def generate(publication: Path, output: Path) -> dict[str, Any]:
    inputs = {
        "llvm": publication / "external-corpus" / "benchmark_results.csv",
        "examples": publication / "final" / "benchmark_results.csv",
        "modules": publication / "case-studies" / "benchmark_results.csv",
        "example_ablations": publication / "ablation" / "benchmark_results.csv",
        "module_ablations": publication / "case-study-ablation" / "benchmark_results.csv",
        "c2rust": publication / "c2rust-only" / "benchmark_results.csv",
    }
    missing = [path for path in inputs.values() if not path.is_file()]
    if missing:
        raise FileNotFoundError("Missing manuscript input(s): " + ", ".join(map(str, missing)))
    source_commit = _verify_provenance(list(inputs.values()))
    output.mkdir(parents=True, exist_ok=True)
    cascade = [
        _cascade("LLVM programs", inputs["llvm"]),
        _cascade("Microbenchmarks", inputs["examples"]),
        _cascade("Authored modules", inputs["modules"]),
    ]
    cascade_path = output / "development_cascade.tex"
    ablation_path = output / "development_ablations.tex"
    _write_cascade(cascade_path, cascade)
    ablations = _write_ablations(
        ablation_path, inputs["example_ablations"], inputs["module_ablations"]
    )
    audit_path = output.parent / "DEVELOPMENT_RESULT_AUDIT.md"
    _write_audit(audit_path, source_commit, inputs, cascade, ablations)
    manifest = {
        "schema_version": "safemap.manuscript_tables.v1",
        "source_git_commit": source_commit,
        "inputs": {
            name: {"path": _display_path(path), "sha256": _sha256(path)}
            for name, path in inputs.items()
        },
        "development_cascade": [
            {"corpus": label, "values": values} for label, values in cascade
        ],
        "development_ablations": ablations,
        "outputs": {
            cascade_path.name: _sha256(cascade_path),
            ablation_path.name: _sha256(ablation_path),
            _display_path(audit_path): _sha256(audit_path),
        },
    }
    (output / "manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--publication", type=Path, default=DEFAULT_PUBLICATION)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    result = generate(args.publication.resolve(), args.output.resolve())
    print(json.dumps(result, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
